### ISSUE TITLE
Technical Challenges

### ISSUE THREAD

**Issue by EricaThompson** [EricaThompson/dreamers#3]
Backend Challenges: MongoDB/Express

* 
* 
* 
* 
* 
* 

Frontend Challenges: React/Node.js

*
*
*
*
*
*

Other Challenges:
We encountered an issue working with the .eslintcache file while working with version control, we found that we have to .gitignore it or else it will cause file-change issues while checking out other branches and merging. We also found that if a file has ever been checked in for Git version control, it can not be later ignored unless it's removed from the version control cache.

**Comment by AlanDai** [comment]
BE: UAuth
- We ran into a bug where POST req bodies (req.body) were returning 'undefined'. The problem we found was that we needed some way to parse the body of the request. To do this, we installed the body-parser module, which had been removed from express relatively recently. Another possible solution is to use express' replacement for body-parser via `app.use(express.json())` - we'll come back to this later.

**Comment by AlanDai** [comment]
BE: Dreams CRUD
- While testing the update dream route on Postman, we kept running into a bug where the request body would include an extra key/value pair (text:''). We played around with changing the actual model and in Postman but ended up just adding an extra filter for that key/value pair. This worked out because empty text values are already filtered out via the validations on the update dream inputs. Why this bug keeps happening, we're still not sure, but we have a working solution in place.

**Comment by AlanDai** [comment]
BE: Tags
- We had a bit of an engineering decision regarding how to handle tags in the database. Our original plan was to keep an array of tag ids to keep track of all tags associated with a dream (dreams are like tweets with tags) but we realized that to grab any dream, we would have to perform additional queries into the tag collection for each tag associated with the dream. Instead, because the tag data was fairly simple, we kept track of a dream's tags with the actual tag string.
- This led to a design decision on the frontend on how to handle tags. We wanted to split the tag creation and dream creation process. To do this, we created new backend routes for tag creation to match up with a tag input field on the dream form. One major consequence of this decision was that we could now validate tag inputs one at a time and return errors on the form itself without actually having to submit the full dream.

**Comment by joshkohane** [comment]
FE: Modal

- Needed to send props to modal, but since it is never called directly from another page it was difficult to get them there. Since the modal has a container, it is no problem to send methods directly to it, but data needed to come from a specific place.
- In order to get data to the modal, we added actions and a modal info reducer that only stored the necessary information needed by each modal. This action is used in a handleOpenModal function that send information to the modal info slice of state, therefore allowing it to be used anywhere in the app, and more specifically, by the correct modal.

**Comment by AlanDai** [comment]
BE: Search
- We ran into the question of how to properly handle multiple queries within a single Express route. Our original plan was to chain promises but we realized chaining queries was probably poor form. Our solution was to use `Promse.all(queries, cb))` to aggregate the results from all the queries so that we could send a single response with all the query results.
